---
# This sets up the basic system

- name: Install ntp
  apt: name=ntp state=present
  tags: ntp

- name: Configure ntp
  template: src=ntp.conf.j2 dest=/etc/ntp.conf
  tags: ntp
  notify: restart ntp

- name: Start ntp
  service: name=ntpd state=started enabled=true
  tags: ntp

- name: Install tools
  apt: name={{item}} state=present
  with_items:
    - vim
    - vim-scripts
    - tig
    - etckeeper

- name: Install vim configuration
  copy: src=vimrc.local dest=/etc/vim/vimrc.local

- name: Install yaml highlighting
  copy: src=yaml.vim dest=/etc/vim/yaml.vim


