---
# This sets up the basic system

- name: Update apt cache
  apt: update_cache=yes

- name: Upgrade all safe packages
  apt: upgrade=safe

- name: Install tools
  apt: name={{item}} state=present
  with_items:
    - ntp
    - vim
    - vim-scripts
    - git
    - tig
    - etckeeper
    - screen
    - zsh
    - build-essential

- name: Configure ntp
  template: src=ntp.conf.j2 dest=/etc/ntp.conf
  tags: ntp
  notify: restart ntp

- name: Start ntp
  service: name=ntp state=started enabled=true
  tags: ntp

- name: Install vim configuration
  copy: src=vimrc.local dest=/etc/vim/vimrc.local

- name: Install yaml highlighting
  copy: src=yaml.vim dest=/etc/vim/yaml.vim


