---
# Set up a mail server

# goal:
# - secure imap mail server
# - stores mail in maildir format
# - can POP mail from other accounts
# - can backup popped mail to other locations
# - installed on a VPS
# - mails are backuped to many locations (google drive?, copy.com?)


- name: install packages
  apt: name={{item}} state=present
  with_items:
    - dovecot-core
    - dovecot-imapd
    - dovecot-lmtpd
    - dovecot-sieve
    - dovecot-managesieved
    - sasl2-bin
    - postfix
    - fetchmail
    - procmail

# configure postfix
- name: install postfix main.cf
  template: src=main.cf.j2 dest=/etc/postfix/main.cf

# configure procmail
- name: install procmailrc
  copy: src=procmailrc dest=/etc/procmailrc owner=root

# configure fetchmail
- name: install fetchmailrc
  copy: src=fetchmailrc dest=/etc/fetchmailrc owner=root mode=600

# configure dovecot



