---
# Set up a mail server

# goal:
# - secure imap mail server
# - stores mail in maildir format
# - can POP mail from other accounts
# - can backup popped mail to other locations
# - installed on a VPS
# - mails are backuped to many locations (google drive?, copy.com?)


- name: install packages
  apt: name={{item}} state=present
  with_items:
    - dovecot-core
    - dovecot-imapd
    - dovecot-lmtpd
    - dovecot-sieve
    - dovecot-managesieved
    - libsasl2-modules
    - sasl2-bin
    - postfix
    - fetchmail
    - procmail
    - mutt

# configure postfix
- name: install postfix main.cf
  template: src=main.cf.j2 dest=/etc/postfix/main.cf owner=root group=root
  notify: restart postfix

- name: install postfix master.cf
  copy: src=master.cf dest=/etc/postfix/master.cf owner=root group=root
  notify: restart postfix

# configure procmail
- name: install procmailrc
  copy: src=procmailrc dest=/etc/procmailrc owner=root group=root

# configure fetchmail
#- name: install fetchmailrc
#  template: src=fetchmailrc.j2 dest=/etc/fetchmailrc owner=root group=root mode=600

# configure dovecot
- name: install dovecot.conf
  copy: src=dovecot.conf dest=/etc/dovecot/dovecot.conf

- name: install dovecot configuration files
  copy: src={{item}} dest=/etc/dovecot/conf.d/{{item}}
  with_items:
    - 10-mail.conf
    - 10-auth.conf
    - 10-master.conf
    - 10-ssl.conf
    - 20-imap.conf
    - 20-lmtp.conf
    - 20-managesieve.conf
    - 90-sieve.conf
  notify: restart dovecot

- name: install dovecot lda configuration
  template: src=15-lda.conf.j2 dest=/etc/dovecot/conf.d/15-lda.conf
  notify: restart dovecot

